{
 "title": "P1 Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Power", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(instantaneous_power_positive_kw) without (phase) * 1000"
    }
   ]
  },
  {
   "title": "L1",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "expr": "instantaneous_power_positive_kw{phase=\"L1\"} * 1000"
    }
   ]
  },
  {
   "title": "L2",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "expr": "instantaneous_power_positive_kw{phase=\"L2\"} * 1000"
    }
   ]
  },
  {
   "title": "L3",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "expr": "instantaneous_power_positive_kw{phase=\"L3\"} * 1000"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "current_electricity_tariff" }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "instantaneous_power_positive_kw * 1000",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "sum(instantaneous_power_positive_kw) without (phase) * 1000",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Energy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Energy used (30min)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "watth" }
   ],
   "targets": [
    {
     "expr": "increase(electricity_used_kwh[30m]) * 1000",
     "legendFormat": "Tariff {{tariff}}"
    }
   ]
  },
  {
   "title": "Total (24h)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 16 },
   "format": "watth",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(electricity_used_kwh[24h])) without (tariff) * 1000"
    }
   ]
  },
  {
   "title": "High tariff (24h)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 16 },
   "format": "watth",
   "valueName": "current",
   "targets": [
    {
     "expr": "increase(electricity_used_kwh{tariff=\"2\"}[24h]) * 1000"
    }
   ]
  },
  {
   "title": "Low tariff (24h)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 16 },
   "format": "watth",
   "valueName": "current",
   "targets": [
    {
     "expr": "increase(electricity_used_kwh{tariff=\"1\"}[24h]) * 1000"
    }
   ]
  },
  {
   "title": "Total (all time)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 19 },
   "format": "watth",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(electricity_used_kwh) without (tariff) * 1000"
    }
   ]
  },
  {
   "title": "High tariff (all time)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 19 },
   "format": "watth",
   "valueName": "current",
   "targets": [
    {
     "expr": "electricity_used_kwh{tariff=\"2\"} * 1000"
    }
   ]
  },
  {
   "title": "Low tariff (all time)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 19 },
   "format": "watth",
   "valueName": "current",
   "targets": [
    {
     "expr": "electricity_used_kwh{tariff=\"1\"} * 1000"
    }
   ]
  },
  { "title": "Gas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Gas used (30min)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "m3" }
   ],
   "targets": [
    { "expr": "increase(gas_used_m3[30m])", "legendFormat": "Gas" }
   ]
  },
  {
   "title": "Total (all time)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 23 },
   "format": "m3",
   "valueName": "current",
   "targets": [
    { "expr": "gas_used_m3" }
   ]
  },
  {
   "title": "Total (last 24h)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 26 },
   "format": "m3",
   "valueName": "current",
   "targets": [
    { "expr": "increase(gas_used_m3[24h])" }
   ]
  }
 ]
}